// Code generated by protoc-gen-go. DO NOT EDIT.
// source: platform/output.proto

package platform

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// You can customise this message to change the fields for
// the output value from your Deployment
type Deployment struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The AWS region the function is deployed in
	Region string `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	// The ARN for the Lambda function itself.
	FuncArn string `protobuf:"bytes,4,opt,name=func_arn,json=funcArn,proto3" json:"func_arn,omitempty"`
	// The ARN for the version of the Lambda function this deployment uses.
	VerArn string `protobuf:"bytes,5,opt,name=ver_arn,json=verArn,proto3" json:"ver_arn,omitempty"`
	// The version identifier AWS uses for this version (basically a serial increasing number)
	Version              string   `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Deployment) Reset()         { *m = Deployment{} }
func (m *Deployment) String() string { return proto.CompactTextString(m) }
func (*Deployment) ProtoMessage()    {}
func (*Deployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e5234dca2919ebb, []int{0}
}

func (m *Deployment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deployment.Unmarshal(m, b)
}
func (m *Deployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deployment.Marshal(b, m, deterministic)
}
func (m *Deployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deployment.Merge(m, src)
}
func (m *Deployment) XXX_Size() int {
	return xxx_messageInfo_Deployment.Size(m)
}
func (m *Deployment) XXX_DiscardUnknown() {
	xxx_messageInfo_Deployment.DiscardUnknown(m)
}

var xxx_messageInfo_Deployment proto.InternalMessageInfo

func (m *Deployment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Deployment) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Deployment) GetFuncArn() string {
	if m != nil {
		return m.FuncArn
	}
	return ""
}

func (m *Deployment) GetVerArn() string {
	if m != nil {
		return m.VerArn
	}
	return ""
}

func (m *Deployment) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*Deployment)(nil), "platform.Deployment")
}

func init() {
	proto.RegisterFile("platform/output.proto", fileDescriptor_1e5234dca2919ebb)
}

var fileDescriptor_1e5234dca2919ebb = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0xc8, 0x49, 0x2c,
	0x49, 0xcb, 0x2f, 0xca, 0xd5, 0xcf, 0x2f, 0x2d, 0x29, 0x28, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x80, 0x09, 0x2b, 0x35, 0x31, 0x72, 0x71, 0xb9, 0xa4, 0x16, 0xe4, 0xe4, 0x57,
	0xe6, 0xa6, 0xe6, 0x95, 0x08, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0x31, 0x65, 0xa6, 0x08, 0x89, 0x71, 0xb1, 0x15, 0xa5, 0xa6, 0x67, 0xe6, 0xe7, 0x49, 0x30,
	0x83, 0xc5, 0xa0, 0x3c, 0x21, 0x49, 0x2e, 0x8e, 0xb4, 0xd2, 0xbc, 0xe4, 0xf8, 0xc4, 0xa2, 0x3c,
	0x09, 0x16, 0xb0, 0x0c, 0x3b, 0x88, 0xef, 0x58, 0x94, 0x27, 0x24, 0xce, 0xc5, 0x5e, 0x96, 0x5a,
	0x04, 0x96, 0x61, 0x85, 0xe8, 0x29, 0x4b, 0x2d, 0x02, 0x49, 0x48, 0x80, 0x25, 0x8a, 0x41, 0x86,
	0xb1, 0x41, 0xb4, 0x40, 0xb9, 0x4e, 0x9a, 0x51, 0xea, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a,
	0xc9, 0xf9, 0xb9, 0xfa, 0x05, 0x19, 0xf9, 0x49, 0x89, 0x79, 0x06, 0x86, 0xfa, 0x39, 0x89, 0xb9,
	0x49, 0x29, 0x89, 0xba, 0xa9, 0x15, 0x25, 0xfa, 0x30, 0xf7, 0x26, 0xb1, 0x81, 0x3d, 0x60, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x55, 0x8a, 0xf3, 0x75, 0xd9, 0x00, 0x00, 0x00,
}
